### ISSUE TITLE
stack build, stack.yaml

### ISSUE THREAD

**Issue by bgyuris** [stschiff/rarecoal-tools#1]
Dear Stephan!
I have tried installing rarecoal-tools but got this error message after stack build:

Could not parse '/home/genelab/rarecoal-tools-master/stack.yaml':
Aeson exception:
Error in $.packages[0]: failed to parse field 'packages': parsing Text failed, expected String, but encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/

Stack worked fine for rarecoal it only happened at tools. The stack.yaml seems different in rarecoal and rarecoal-tools. Do you have any idea how to resolve this? 

Thanks

**Comment by stschiff** [comment]
Sorry. I've just updated the `stack.yaml` file. It should work now.
